services:
  frontend:
    build:
      context: ./stockchat-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    networks:
      - stockchat-network

  backend:
    build:
      context: ./stockchat-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./stockchat-backend/.env
    volumes:
      - ./stockchat-backend:/app
      - ./data:/app/data
    networks:
      - stockchat-network

networks:
  stockchat-network:
    driver: bridge

volumes:
  data: 